#!/usr/bin/env python3
# Generates data_vfxmacc.h for vfxmacc.vf tests (fp32 only)

import argparse
import math
import random
from typing import List


def ceil_div(a: int, b: int) -> int:
    return (a + b - 1) // b


def pack_indices_bitstream(indices: List[int], idx_width: int) -> List[int]:
    """
    Pack `indices` (each fits in idx_width bits) into an array of uint32 words.
    Layout: little-endian bit packing within the stream:
      indices[0] in lowest bits of word0, then indices[1], ...
    """
    total_bits = len(indices) * idx_width
    num_words = ceil_div(total_bits, 32)
    words = [0] * num_words

    bitpos = 0
    mask = (1 << idx_width) - 1
    for v in indices:
        v &= mask
        w = bitpos // 32
        o = bitpos % 32

        # write across word boundary if needed
        if o + idx_width <= 32:
            words[w] |= (v << o)
        else:
            lo_bits = 32 - o
            hi_bits = idx_width - lo_bits
            lo_mask = (1 << lo_bits) - 1
            words[w] |= ((v & lo_mask) << o)
            words[w + 1] |= (v >> lo_bits) & ((1 << hi_bits) - 1)

        bitpos += idx_width

    # Ensure uint32 range
    return [w & 0xFFFFFFFF for w in words]


def gen_indices_for_nm(avl: int, n: int, m: int, seed: int) -> List[int]:
    """
    For each block of size m, choose n unique positions.
    We generate exactly `avl` indices total, so number of blocks = avl / n must be integer.
    """
    if avl % n != 0:
        raise ValueError(f"AVL ({avl}) must be divisible by n ({n}) so blocks = AVL/n is integer.")

    rng = random.Random(seed)
    blocks = avl // n
    indices = []
    for _ in range(blocks):
        picks = rng.sample(range(m), n)  # unique positions inside the block
        # Keep a stable order to reduce “randomness chaos” in debugging:
        picks.sort()
        indices.extend(picks)
    return indices  # length = avl


def gen_a_fp32(avl: int, seed: int) -> List[float]:
    rng = random.Random(seed ^ 0xA5A5_1234)
    # modest range to avoid big rounding issues
    return [rng.uniform(-3.0, 3.0) for _ in range(avl)]


def compute_golden(a: List[float], indices: List[int], n: int, m: int, b: float) -> List[float]:
    avl = len(a)
    orig_len = avl * m // n
    golden = [0.0] * orig_len

    blocks = avl // n
    k = 0
    for blk in range(blocks):
        base = blk * m
        for _ in range(n):
            pos = base + indices[k]
            golden[pos] += b * a[k]
            k += 1
    return golden


def c_array_floats(name: str, arr: List[float], per_line: int = 8) -> str:
    out = [f"static const float {name}[{len(arr)}] __attribute__((aligned(64))) = {{"]  # 64B align helps DMA
    for i, v in enumerate(arr):
        if i % per_line == 0:
            out.append("  ")
        out[-1] += f"{v:.8e}f"
        if i != len(arr) - 1:
            out[-1] += ", "
        if (i % per_line == per_line - 1) and (i != len(arr) - 1):
            out.append("")
    out.append("\n};\n")
    return "\n".join(out)


def c_array_u32(name: str, arr: List[int], per_line: int = 6) -> str:
    out = [f"static const uint32_t {name}[{len(arr)}] __attribute__((aligned(64))) = {{"]  # 64B align helps DMA
    for i, v in enumerate(arr):
        if i % per_line == 0:
            out.append("  ")
        out[-1] += f"0x{v:08x}u"
        if i != len(arr) - 1:
            out[-1] += ", "
        if (i % per_line == per_line - 1) and (i != len(arr) - 1):
            out.append("")
    out.append("\n};\n")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=2, help="n in n:m (default 2)")
    ap.add_argument("--m", type=int, default=4, help="m in n:m (default 4)")
    ap.add_argument("--avl", type=int, default=32, help="AVL = number of nonzeros (default 32)")
    ap.add_argument("--b", type=float, default=2.0, help="scalar multiplier b used by vfxmacc.vf (default 2.0)")
    ap.add_argument("--seed", type=int, default=1, help="random seed (default 1)")
    ap.add_argument("--out", type=str, default="data_vfxmacc.h", help="output header filename")
    args = ap.parse_args()

    n, m, avl, b, seed = args.n, args.m, args.avl, args.b, args.seed

    if n <= 0 or m <= 0:
        raise ValueError("n and m must be positive.")
    if n > m:
        raise ValueError("Require n <= m.")
    if (avl * m) % n != 0:
        raise ValueError("Require ORIG_LEN = AVL*m/n to be integer (choose AVL accordingly).")

    idx_width = math.ceil(math.log2(m)) if m > 1 else 1
    orig_len = avl * m // n

    indices = gen_indices_for_nm(avl, n, m, seed)
    a = gen_a_fp32(avl, seed)
    golden = compute_golden(a, indices, n, m, b)
    nm_words = pack_indices_bitstream(indices, idx_width)

    guard = "DATA_VFXMACC_H"
    header = []
    header.append("// Auto-generated by gen_vfxmacc_data.py")
    header.append(f"// n:m = {n}:{m}, AVL(nonzeros)={avl}, ORIG_LEN={orig_len}, IDX_WIDTH={idx_width}, b={b}")
    header.append("")
    header.append(f"#ifndef {guard}")
    header.append(f"#define {guard}")
    header.append("")
    header.append("#include <stdint.h>")
    header.append("")
    header.append(f"#define N             ({n})")
    header.append(f"#define M             ({m})")
    header.append(f"#define AVL_NNZ       ({avl})")
    header.append(f"#define IDX_WIDTH     ({idx_width})")
    header.append(f"#define ORIG_LEN      ({orig_len})")
    header.append(f"#define NM_INDEX_WORDS ({len(nm_words)})")
    header.append(f"#define VFXMACC_B     ({b}f)")
    header.append("")
    header.append("// a_dram: compact FP32 input vector of length AVL_NNZ")
    header.append("// nm_index_dram: bit-packed indices, IDX_WIDTH bits per nonzero")
    header.append("// golden_dram: scattered FP32 golden output of length ORIG_LEN (init=0, then += b*a at indexed positions)")
    header.append("")
    header.append(c_array_floats("a_dram", a))
    header.append(c_array_u32("nm_index_dram", nm_words))
    header.append(c_array_floats("golden_dram", golden))
    header.append(f"#endif // {guard}\n")

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(header))

    print(f"Wrote {args.out}")
    print(f"  n:m={n}:{m}, AVL_NNZ={avl}, ORIG_LEN={orig_len}, IDX_WIDTH={idx_width}, NM_INDEX_WORDS={len(nm_words)}")


if __name__ == "__main__":
    main()
